server:
  port: 8081

# Configure Spring specific properties
spring:

  application:
    name: account-service

  # Enable/Disable hot swapping
  devtools:
    restart:
      enabled: true
      log-condition-evaluation-delta: false

  # Datasource Configurations
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017/proactive
      database: proactive
  
  cloud:
    config:
      enabled:
        false
      
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8061/eureka