spring:
  datasource:
    url: jdbc:mysql://localhost:3306/products_dev_db
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size:  100
          order_inserts: true
