version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - mynet
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    networks:
      - mynet
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.204.106.55
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LOG_DIRS: /tmp/kafka_mounts/logs
      KAFKA_CREATE_TOPICS: "transactions:1:2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8090:8080"
    networks:
      - mynet
    depends_on:
      - zookeeper
      - kafka
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
  reactive-banking-service:
    build: ./reactive-banking-service
    ports:
      - "8080:8080"
    networks:
      - mynet
    depends_on:
      - zookeeper
      - kafka
      - reactive-user-notification-service
      - reactive-reporting-service
      - reactive-account-management-service
  reactive-user-notification-service:
    build: ./reactive-user-notification-service
    ports:
      - "8081:8081"
    depends_on:
      - zookeeper
      - kafka
  reactive-reporting-service:
    build: ./reactive-reporting-service
    ports:
      - "8082:8082"
    networks:
      - mynet
    depends_on:
      - zookeeper
      - kafka
  reactive-account-management-service:
    build: ./reactive-account-management-service
    ports:
      - "8083:8083"
    networks:
      - mynet
    depends_on:
      - zookeeper
      - kafka
